### ISSUE TITLE
Equivalent to perform_in for the run method?

### ISSUE THREAD

**Issue by jeremysmithco** [doximity/simplekiq#26]
Hey all! I've been using Simplekiq for several months and love it. ❤️ I hit an interesting challenge this past week and had an idea. I have an orchestration job that looks something like this:

```ruby
class OrchestrateFooBarJob
  include Simplekiq::OrchestrationJob

  def perform_orchestration(id)
    foo = Foo.find(id)
    return if foo.complete?

    in_parallel do
      foo_bar_ids = foo.foo_bars.ids # Foo has_many :foo_bars
      foo_bar_ids.each do |foo_bar_id|
        run FooBarJob, foo_bar_id
      end
    end
  end
end
```

Each `FooBarJob` makes an API request and stores some data on the `FooBar` AR model. The problem is, during peak app usage, there may be several `OrchestrateFooBarJob` jobs running at a time, firing off many parallel `FooBarJob` jobs nearly simultaneously and exceeding our API request concurrency.

We've upgraded to Sidekiq Enterprise and I'm about to implement [Concurrent Rate Limiting](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#concurrent) on the `FooBarJob` class. But in my mind, ideally I wouldn't be relying solely on the `OverLimit` exceptions plus a backoff with jitter.

As the docs say under [Limiting is not Throttling](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#limiting-is-not-throttling):
>If you push 1000 jobs to Redis, Sidekiq will run those jobs as fast as possible which may cause many of those jobs to fail with an OverLimit error. If you want to trickle jobs into Sidekiq slowly, the only way to do that is with manual scheduling. Here's how you can schedule 1 job per second to ensure that Sidekiq doesn't run all jobs immediately:
>
>```
>1000.times do |index|
>  SomeWorker.perform_in(index, some_args)
>end
>```

Looking at the [Batches docs Notes section](https://github.com/mperham/sidekiq/wiki/Batches#notes), I see that:
>Batches can contain scheduled jobs too, e.g. `perform_in(10.minutes)`.

So, now I'm wondering, would it be possible (and make sense) to have a `run` command equivalent for `perform_in`, something like `run_in` below?

```ruby
class OrchestrateFooBarJob
  include Simplekiq::OrchestrationJob

  def perform_orchestration(id)
    foo = Foo.find(id)
    return if foo.complete?

    in_parallel do
      foo_bar_ids = foo.foo_bars.ids
      foo_bar_ids.each_with_index do |foo_bar_id, i|
        run_in i.seconds, FooBarJob, foo_bar_id
      end
    end
  end
end
```

Or have you maybe found another way to solve this?

**Comment by jacknoble** [comment]
Hey Jeremy! Thanks for submitting. Your issue makes sense and the proposed API is reasonable. We've noticed a few times now that the current `run Job, *args` api makes it tricky to add Sidekiq options and things like perform_in. We'll kick this around at get back to you!

**Comment by jeremysmithco** [comment]
Thanks Jack! That makes sense. I had wondered if a different API that allowed passing options to the `set` method might make it more versatile and generally useful.

BTW, I'd classify this as a nice-to-have, but not a blocker on my project. 👍 Thanks again!

**Comment by jcwilk** [comment]
Hi @jeremysmithco - we had a good amount of discussion about this internally as the ask dovetails with some unrelated sidekiq-oriented code from another part of the company which may get released sometime soon which provides something very similar to what you're asking for here (I've been calling it "preemptive backoff") however the code in question there may end up being more sidekiq via `ActiveJob` oriented and less `sidekiq-pro` oriented, leveraging the queue order as the main source of "natural backpressure" which probably wouldn't be a mechanism that would fit your needs since various mechanisms within sidekiq can perturb that ordering (failure retries, requeuing due to deploy restarts, requeuing due to limiter usage) which would make adhering to a strict rate limit, especially a global one, very difficult, although it does seem to be a promising, simple solution for long running backqueues and things of that nature which don't have specific rate limiting limitations.

If you want to keep an eye out for that library though, it'll likely get released under the name of "SuperSpreader" but the primary contributor has a lot on their plate so it's uncertain when it'll hit the wire.

We're in general a bit wary of changing the signature of `run` because the underlying workflow data structure it leads to ends up getting persisted into misc sidekiq-pro callbacks under the hood so we have to be very cautious about not ever breaking prior formats and making sure we plan to support new formats forever... So basically, super high cost in churn on changes to `run` behavior so we want to save that for really high value, essential features, and since `simplekiq` is very much so oriented around being reactively batch callback driven rather than trying to anticipate optimal batching behavior up front it doesn't quite fit into the spirit of the project, or at least not enough to justify the `run` churn at this time.

However, there is an approach to doing what you're asking via using basic `sidekiq-pro` batching mechanisms, with or without `simplekiq`, the pseudocode is something like:

1. create a sidekiq-pro batch of jobs containing the next subset of the total work to be done
2. create an on success callback on that batch
3. make the callback be step 1 so it create the next batch, the next callback, etc, etc

We've been playing with different names and so far have been calling this "recursive batching" or in the case of simplekiq, "sleepy orchestrations" ("sleepy" because it works for awhile on a batch and then "sleeps" until the batch finishes and the callback makes it to the top of the queue and makes a new batch). You can do this in simplekiq orchestrations too:

```ruby
class SomeSleepyOrchestration
  include Sidekiq::Worker
  include Simplekiq::OrchestrationJob

  def perform_orchestration(min_id)
    return if all_done_with_processing?(min_id) # the base case of the "recursion"

    items_to_process = SomeQuery.items_to_process(some_arg)

    in_parallel do
      items_to_process.each do |element|
        run SomeChildJob, element
      end
    end

    run SomeSleepyOrchestration, items_to_process.max + 1 # "recursively" iterate one batch further
  end
end
```

Something like that - apologies if there's a bug in there, didn't check it but I think that captures the idea fairly well. The trick is you want `items_to_process` to return a limited batch size where the batch size is large enough that your workload isn't constantly waiting for the last job or two from a small batch to finish and the callback to work its way through, but small enough so that you're not flooding your queue with too many jobs at once. No magic number here, just depends on the nature of the other jobs in your queue, workers count, etc...

And of course you'll want some kind of emergency braking mechanism so it can't spin off out of control, it can be a little difficult to stop orchestrations like this sometimes (keep an eye out for future features around [invalidation](https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch) - although you can implement this yourself as described in the link, we do that ourselves for now until we can come up with a generalized approach)

Huge benefit here is you can just use a `sidekiq-ent` limiter and don't need to worry about overlapping orchestrations or anything like that since you can configure your limiter however you want and it'll Just Work without the system needing to plan ahead on timings correctly. And this of course can be done without `simplekiq` but we've found some amount of success in the sleepy format above, albeit with a fairly high degree of opaqueness in how it works without a lot of explanation - we may turn this kind of thing into a proper `simplekiq` abstraction eventually, but we're going to keep iterating on it from the shadows for a bit :P Do let us know if you find a good/better solution to your problem though... This type of thing is something we constantly are fumbling around with as well and there's a lot of different ways to slice it.

**Comment by benjaminoakes** [comment]
👋 I'm the author of SuperSpreader.  Please let me know if that's of interest.  There are quite a few other things going on on my side, but I'm very interested in open sourcing once some other work is out of the way.

SuperSpreader was built for a specific use case: parallel backfilling of many millions of records in Ruby-land.  If that's what you're trying to do, it may be a very good fit.

**Comment by jeremysmithco** [comment]
@jcwilk Thanks so much for the detailed reply! This feels like the hidden knowledge about working with background jobs that you just can't find in blog posts. 😊 Thanks for sharing the idea of recursive batches. That approach hadn't occurred to me. I'll probably just keep leaning on Limiter for now, but that gives me another option. 👍

> We're in general a bit wary of changing the signature of run because the underlying workflow data structure it leads to ends up getting persisted into misc sidekiq-pro callbacks under the hood so we have to be very cautious about not ever breaking prior formats and making sure we plan to support new formats forever...

Makes total sense!

**Comment by jeremysmithco** [comment]
@benjaminoakes Hey, thanks for reaching out!

>SuperSpreader was built for a specific use case: parallel backfilling of many millions of records in Ruby-land. If that's what you're trying to do, it may be a very good fit.

I don't _think_ that's quite my use-case, and definitely not at that scale. But I'm interested, and I'll keep an eye out for the release. Thanks!
